### ISSUE TITLE
cannot run tests and examples from the directory above it. 

### ISSUE THREAD

**Issue by sannecottaar** [geodynamics/burnman#112]
I have no clue what changed, but all of a sudden I'm having trouble running test.sh as the tests will fail to import burman. The only way I can fix this is to force a switch in directory:
abspath = os.path.abspath(__file__)
dname = os.path.dirname(abspath)
os.chdir(dname)
Does anybody have a clue or a better solution?

**Comment by tjhei** [comment]
error message?

**Comment by sannecottaar** [comment]
python tests/test_*.py  or python examples/example_* gives
Traceback (most recent call last):
  File "examples/example_averaging.py", line 39, in <module>
    import burnman
ImportError: No module named burnman

**Comment by sannecottaar** [comment]
The sys.path... function adds the parent directory of my current directory.

**Comment by tjhei** [comment]
> File "examples/example_averaging.py",

Are you running it from the parent directory as ```python example_averaging.py```? That never worked. 

Note that test.sh moves into the subdirectories before executing tests and examples.

**Comment by sannecottaar** [comment]
Ok, so maybe my test.sh is only failing because I don't have numdiff...

**Comment by tjhei** [comment]
Probably also because some stuff is broken on MAC. Can you post your output?

**Comment by sannecottaar** [comment]
!  example_averaging.py ... FAIL
readlink: illegal option -- f
usage: readlink [-n] [file ...]
readlink: illegal option -- f
usage: readlink [-n] [file ...]
Check:
test.sh: line 37: numdiff: command not found
test.sh: line 33: numdiff: command not found

**Comment by tjhei** [comment]
> readlink: illegal option -- f

I am using something that doesn't work on MAC. Hrm.

> test.sh: line 37: numdiff: command not found

you need numdiff.

**Comment by tjhei** [comment]
Please see #113.

**Comment by tjhei** [comment]
what is your test.sh output now?

**Comment by sannecottaar** [comment]
Here is part:
  benchmark.py ... ok
  chemical_potential_benchmarks.py ... ok
!  debye.py ... FAIL
Check:
/Users/sanne/Documents/Research/Side_projects/burnman/misc/benchmarks/debye.py.tmp
/Users/sanne/Documents/Research/Side_projects/burnman/misc/ref/debye.py.out
1c1
< error 7.009821e-14
---
> error 7.013244e-14

**Comment by sannecottaar** [comment]
Other parts give issues because of grep and _text2path, but I try to look
through those.

**Comment by tjhei** [comment]
> Other parts give issues because of grep and _text2path, but I try to look through those.

post the output please.

**Comment by sannecottaar** [comment]
30 times (or so):
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
    [-e pattern] [-f file] [--binary-files=value] [--color=when]
    [--context[=num]] [--directories=action] [--label] [--line-buffered]
    [--null] [pattern] [file ...]
And this error has been around for a while, since I cannot reproduce the
makeup of the published images:
Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
  File "paper_uncertainty.py", line 146, in <module>
    plt.savefig("uncertain.pdf",bbox_inches='tight')
  File
"/Users/sanne/anaconda/lib/python2.7/site-packages/matplotlib/pyplot.py",
line 577, in savefig
    draw()   # need this if 'transparent=True' to reset colors
  File
"/Users/sanne/anaconda/lib/python2.7/site-packages/matplotlib/pyplot.py",
line 570, in draw
    get_current_fig_manager().canvas.draw()
  File
"/Users/sanne/anaconda/lib/python2.7/site-packages/matplotlib/backends/backend_template.py",
line 238, in draw
    self.figure.draw(renderer)
  File
"/Users/sanne/anaconda/lib/python2.7/site-packages/matplotlib/artist.py",
line 59, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File
"/Users/sanne/anaconda/lib/python2.7/site-packages/matplotlib/figure.py",
line 1079, in draw
    func(*args)
  File
"/Users/sanne/anaconda/lib/python2.7/site-packages/matplotlib/artist.py",
line 59, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File
"/Users/sanne/anaconda/lib/python2.7/site-packages/matplotlib/axes/_base.py",
line 2092, in draw
    a.draw(renderer)
  File
"/Users/sanne/anaconda/lib/python2.7/site-packages/matplotlib/artist.py",
line 59, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File
"/Users/sanne/anaconda/lib/python2.7/site-packages/matplotlib/axis.py",
line 1108, in draw
    tick.draw(renderer)
  File
"/Users/sanne/anaconda/lib/python2.7/site-packages/matplotlib/artist.py",
line 59, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File
"/Users/sanne/anaconda/lib/python2.7/site-packages/matplotlib/axis.py",
line 249, in draw
    self.label1.draw(renderer)
  File
"/Users/sanne/anaconda/lib/python2.7/site-packages/matplotlib/artist.py",
line 59, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File
"/Users/sanne/anaconda/lib/python2.7/site-packages/matplotlib/text.py",
line 581, in draw
    self._fontproperties, angle, mtext=mtext)
  File
"/Users/sanne/anaconda/lib/python2.7/site-packages/matplotlib/backend_bases.py",
line 527, in draw_tex
    self._draw_text_as_path(gc, x, y, s, prop, angle, ismath="TeX")
  File
"/Users/sanne/anaconda/lib/python2.7/site-packages/matplotlib/backend_bases.py",
line 625, in _draw_text_as_path
    x, y, s, prop, angle, ismath)
  File
"/Users/sanne/anaconda/lib/python2.7/site-packages/matplotlib/backend_bases.py",
line 585, in _get_text_path_transform
    text2path = self._text2path
AttributeError: 'RendererTemplate' object has no attribute '_text2path'
