### ISSUE TITLE
mineral mixing problem

### ISSUE THREAD

**Issue by lordkman** [geodynamics/burnman#123]
When running composite minerals of composites (see example_composition, example 2), produces error:

  File "example_composition.py", line 79, in <module>
    [minerals.SLB_2011.mg_fe_perovskite(0.2),
TypeError: __init__() takes exactly 1 argument (2 given)

Thoughts?

**Comment by bobmyhill** [comment]
Can you post a MWE?

**Comment by lordkman** [comment]
I can, but example_composition creates the error (I discovered it while training an undergrad to use the code, but wasn't sure how to fix it). It's the second example within the example when Fe-pv or fp solid solutions are calculated. Just set it to true (and the others to false) and it should pop up the error.

**Comment by bobmyhill** [comment]
Nope, all work fine for me.

**Comment by bobmyhill** [comment]
But wait, have you pulled from upstream recently? This looks like a copy of the file from before December...

**Comment by bobmyhill** [comment]
(line 79 should now read "if false:")

**Comment by lordkman** [comment]
That fixed it Bob, thanks! I didn't realize I was that far behind the master on other local machine.
