### ISSUE TITLE
New blurb at top of py files

### ISSUE THREAD

**Issue by bobmyhill** [geodynamics/burnman#124]
Can we decide on a new standard blurb at the top of each file? Something to include CIG, and add 2015? Also, egocentric, I know, but can we add me? :)

We should also change the Github link from burnman.org to the CIG page.

**Comment by ian-r-rose** [comment]
You are right on all counts.

**Comment by tjhei** [comment]
I vote for
```
# This file is part of BurnMan - a lower mantle toolkit.
# Copyright (C) 2012 - 2015 by the BurnMan team, released under the GNU GPL v2 or later.
```
(short)

> We should also change the Github link from burnman.org to the CIG page.

Sure, can you make a PR?

**Comment by bobmyhill** [comment]
Hmmm, I would make a small modification:
```
# This file is part of BurnMan - a thermoelastic and thermodynamic toolkit for the Earth and Planetary Sciences.
# Copyright (C) 2012 - 2015 by the BurnMan team, released under the GNU GPL v2 or later.
```

We've moved a long way beyond the original brief for the project!

**Comment by bobmyhill** [comment]
As for the Github link (the one at the top of the main GH page), I don't think I have the appropriate permissions to change that...

**Comment by tjhei** [comment]
Oh, that one. I think we should keep burnman.org there and figure out a way to prominently link to the CIG page from there.

**Comment by bobmyhill** [comment]
Ok, I'm fine with that...

**Comment by ian-r-rose** [comment]
I think the toplevel text you have written is fine, Bob.

**Comment by bobmyhill** [comment]
Ok, great. I'll wait until we've resolved the other PRs to work on this, as I'd rather not make a mess.

**Comment by sannecottaar** [comment]
Very much approved.

**Comment by lordkman** [comment]
Looks good to me.
