### ISSUE TITLE
reset_state

### ISSUE THREAD

**Issue by bobmyhill** [geodynamics/burnman#127]
At the moment, we have tried to optimise set_state by not resetting state if P,T is the same as stored in memory. 

When we're trying to fit experimental data, sometimes we want to change a parameter and look at the same P, T.  I think it would be useful to have either a separate function, or an optional argument to set state to allow us to calculate at the same P, T if an important parameter has changed. Doing a full param check is probably a bit excessive, so we might also want to add a warning the first time we trip the P, T = P, T old statement.

**Comment by tjhei** [comment]
A function ```reset_state``` is an option (and an implementation in ```Material``` is probably enough). I wonder if the current caching scheme is worth it at all or even slows down things because of the checks/copying. Anybody wants to try it out?

**Comment by ian-r-rose** [comment]
I remember writing the P,T check when doing some sensitivity analyses for various parameters--not too different from what Bob is describing, I think.  My recollection is that it made a difference, performance-wise, though I do not remember how much.

Bob, I'm a little puzzled.  Doesn't the current check also cover the case you are describing?  If I change the params, then call set_state(P,T), that should recalculate everything.  Is the objection to writing P,T again?

If I understand you correctly, then we could just implement in ```Material```:
```
def reset_state():
    do_some_check_for_undefined_pressure_temperature()
    self.set_state(self.pressure, self.temperature)
```
