### ISSUE TITLE
Improve solid solution efficiency

### ISSUE THREAD

**Issue by bobmyhill** [geodynamics/burnman#132]
Currently, solution models have many nested loops, where presumably a matrix operation would be much more efficient...

**Comment by ian-r-rose** [comment]
Thanks for creating the issue, Bob.  I can try to take a crack at this, since I was the one agitating for it.

**Comment by bobmyhill** [comment]
Thanks Ian ... that would be great :)

**Comment by bobmyhill** [comment]
Resolved in #316
