### ISSUE TITLE
Energy contributions to Gibbs

### ISSUE THREAD

**Issue by bobmyhill** [geodynamics/burnman#145]
The Debye model for heat capacity developed by S+LB is great for a lot of simple materials. For others, landau-type transitions lead to spikes in heat capacity (particularly at low temperatures), and other contributions (e.g. magnetic) can also be important. 

I think it might be quite nice to add an excess entropy/heat capacity contribution with a form that makes sense in the framework of magnetism/low T landau transitions. As S = \int Cp/T dT, it would make sense to make this
S_excess = a + bT 
and thus 
Cp_excess = bT (which does a reasonable job in modelling magnetic contributions)

What do we think? Both about the idea, and where it should go? HP2011 already has such terms in the polynomial for Cp and as S_0.

**Comment by ian-r-rose** [comment]
I think that it makes good sense to include other contributions to the entropy and heat capacity (whether due to defect generation, magnetic/electronic effects, or whatever).

I do think that the SLB equation of state should do exactly what is described in SLB2005 (otherwise that is a bit of false advertising). Would you be able to do what you propose by subclassing the relevant equation of state, calling the base class for the lattice vibration part, and then adding whatever excess properties you want?

**Comment by bobmyhill** [comment]
Sure, whatever happens, SLB will remain the same. 

I guess the question is how to work the modifications. I envisage all of these things (Landau, magnetism etc etc etc) being modifications to the basic free energy. When I added the Landau stuff to the H+P EoS (still a bit of a mess), we briefly discussed the possibility of separating the EoS and the additional terms, adding some plug-and-play classes to handle the added complexity independent of the EoS. But I'm not quite sure how to design the code to do this. Things like an excess thermal expansivity might also be useful for an SLB-type EoS.

The easiest method might simply be to allow the user to define some gibbs_excess(pressure, temperature) function that is then evaluated to yield excess H, S, V, a, K, Cp, Cv. In the example above, the term would simply be:

**Comment by bobmyhill** [comment]
I think it would make sense to have something in the mineral class like
self.excess_functions = [['landau', Tcrit, Smax, Vmax], ['magnetic', ..., ...], ['function', 'a + bT+ cT*T']]
Then process this in mineral.py, calling some functions in excess_functions.py to spit out the contributions to gibbs, H, S, V etc. Obviously a user designed function will need a lot of inaccurate numerical differentiation unless we can use sympy to differentiate the expression w.r.t T and P...

What do you think?

**Comment by bobmyhill** [comment]
Looking at this a bit more, it might be a little complicated to fully separate the excess contributions. 
We would probably like to have models for anharmonic, electronic, magnetic and disordering effects on H, S, V etc. The issue is adding contributions which are functions of P, T vs. contributions which are functions of V, T. For example, effects due to displacive phase transitions and spin degeneracy are commonly parameterised in terms of P and T. Meanwhile, electronic contributions arise from a contribution to Cv* (a function of V and T). 

Perhaps the easiest way to proceed would be to get the Landau and magnetic stuff out of the way, and introduce electronic contributions via a new SLB-like base class?


* Cv elec has the form (pi*k)^/3 * g(Ef) * T. 
The electronic density of states g(Ef) is constant at "low" temperatures** but decreases at high temperatures. The curve scales with (V/V0)^2/3. The dependence on V makes Cv (and therefore the electronic contribution to the Gibbs free energy) intimately connected to whichever base EoS we use, so it would be difficult to separate the two. 

** Unlike the Debye temperature, the characteristic electronic temperature q has a value on the order of a few 10000 K. Contributions are therefore small (although not always negligible) at typical lithosphere temperatures, but potentially important in the mantle, and certainly in D''/in the core. Cv elec approaches 2.5R as T -> inf (c.f. Boness et al., 1986 for FCC and HCP iron).

**Comment by lordkman** [comment]
I'm in agreement with your assessment Bob. Double counting can become a problem as we get fancier so going back to SLB-like base classes may be the way to go. It raises the issue though of how fancy we want/need to be while still being able to use BurnMan for science

**Comment by bobmyhill** [comment]
You want to model the core? You're gonna need something fancy! :D

**Comment by lordkman** [comment]
Core!? BurnMan is a LOWER MANTLE toolkit Bob, not lower, lower not mantle toolkit!

**Comment by bobmyhill** [comment]
Ok, for the silicate-oxide mantle, I think we can mostly ignore electronic contributions (although maybe not for FeO?), so a simple(r) P,T-based scheme to deal with Landau (for stishovite) and other non-Debyeness is probably ok.

Having said that, I do seem to remember some build-a-planet type stuff going on a while back, and it's a bit difficult to do that without iron. Iron absolutely requires an electronic contribution.

**Comment by lordkman** [comment]
Yeah, it would be good (and interesting) to quantify the contributions relative to each other. 

Yup, build a planet has the core (and upper mantle!). I need to submit a pull request for this...

**Comment by bobmyhill** [comment]
If you're interested in the effect of electronic contributions on thermoelastic/thermodynamic properties, there's a branch in my repo which may be of interest (https://github.com/bobmyhill/burnman/tree/electronic_Cp). The iron example (in the directory electronic_contribution) runs really slowly at the moment because all of the derivative properties are calculated numerically... I can speed this up a lot when I get round to calculating the analytical expressions, and when we optimize things (which I hope is high on the list for December?)

**Comment by bobmyhill** [comment]
PR opened #185
