### ISSUE TITLE
Public properties

### ISSUE THREAD

**Issue by bobmyhill** [geodynamics/burnman#163]
Currently, mineral.pressure, mineral.temperature and mineral.params can be written by the user. 
This is horrible, because it allows the user to reset apparent temperature (or params, or anything else) without recalculating everything - leading to inconsistencies.

Instead, we should make pressure and temperature settable *only* through set_state, and params only settable through set_params. When set_params gets called, mineral.pressure and mineral.temperature gets deleted.

Same thing for solid solutions.

**Comment by sannecottaar** [comment]
This has been dealt with by making pressure and temperature private. Agreed?

**Comment by bobmyhill** [comment]
Agreed!
