### ISSUE TITLE
Clean out main.py functions

### ISSUE THREAD

**Issue by sannecottaar** [geodynamics/burnman#171]
As well as the other calculate_moduli functions scattered around.

**Comment by ian-r-rose** [comment]
I think `main.velocities_from_rock()` should stick around, but can just call the method in `composite`. Most of the others I agree can go.

**Comment by sannecottaar** [comment]
Do we want to get this one done? We now have some misfit functions floating around in main.py. Do we want a separate file with them, or put them in tools?

**Comment by sannecottaar** [comment]
(I can do this today if we want it before 1.0.)

**Comment by tjhei** [comment]
I would prefer we only do things that are absolutely necessary. Otherwise we keep delaying the release. There is no harm in following up with a second release after important stuff happened.

**Comment by sannecottaar** [comment]
There are still some misfit functions in main.py that I think could go somewhere else, although I don't think we otherwise have a use for main.py (except for allowing main.velocities_from_rock() to stick around)
