### ISSUE TITLE
Cleanup for properties branch

### ISSUE THREAD

**Issue by ian-r-rose** [geodynamics/burnman#173]
- [x] Document and test the ability for setting fractions in different ways. Clean it up.
- [x] Is phase_names used somewhere? Why do we need it? Should it be public?
- [x] Does nesting composites work?
- [x] Deprecate or remove `main.velocities_from_rocks()`
- [x] Remove volume fraction
- [x] Remove set_composition() for now.
- [x] Move check_pairs() to material.py
- [x] Do we need set_averaging_scheme(), or can that just be provided on initialization?
- [x] Should set_method() reset the state? (Yes, for everything)
- [x] Remove composition() for now
- [x] Don't use try/except in unroll()
- [x] Remove evaluate_phase_properties()
- [x] Remove calculate_elastic_properties()
- [x] Remove fugacity and chemical_potentials for now
- [x] TODO: add the thermodynamic potentials in Composite
- [x] Don't set internal variables for material properties
- [x] Document aliases and derived functions for material (Timo)
- [x] Document aliases and derived functions for mineral (Timo)
- [x] Document aliases and derived functions for composite (Timo)
- [x] Copy documentation from base class.
- [x] Remove _calculate_moduli()
- [x] Don't use try/except to for mass_to_molar_fractions
- [x] Test material.material_property() (Timo)
- [x] Make aliases into properties, document them
- [x] Material should set self.name == __tostring or whatever
- [x] Remove mineral.composition()
- [x] Rip out solid solution endmember names and compositions
- [x] remove SolidSolution.composition
- [x] Call new Reuss function in solid solution shear modulus averaging
- [x] Look over example composite

**Comment by sannecottaar** [comment]
Can this be closed?

**Comment by bobmyhill** [comment]
Resolved.
