### ISSUE TITLE
To do in the manual

### ISSUE THREAD

**Issue by sannecottaar** [geodynamics/burnman#219]
- [ ] update list of equations of state (and include references)

Separate question. I'd prefer to keep the code overview out of the manual and just online. I'd never use it myself in this document, and I'm afraid someone one day might print this.

**Comment by sannecottaar** [comment]
Why do I not get a checkbox...

**Comment by tjhei** [comment]
You were missing a space before the box. About the stuff you want removed from the PDF: Do you mean the class/function reference in the end?

**Comment by sannecottaar** [comment]
Yes, that.

**Comment by tjhei** [comment]
#221  should do what you want.
