### ISSUE TITLE
Removing test output

### ISSUE THREAD

**Issue by bobmyhill** [geodynamics/burnman#240]
After running tests, the directory structure is full of annoying output files. They can be removed with the line:
`rm -f */*.error */*/*.error */*-e */*/*-e contrib/tutorial/uncertainty.dat`

Can we write this into the test.sh script somehow? Maybe appending a flag if you want to keep them?
`test.sh --keep_output` would be nice.

**Comment by tjhei** [comment]
What are these "*-e" files? I am not seeing them here.

**Comment by bobmyhill** [comment]
The python files all have empty files with a .tmp-e suffix (e.g. misc/benchmarks/solidsolution_benchmarks.py.tmp-e) on both my mac and linux systems. 
Don't know why. 

In your PR, you don't remove contrib/tutorial/uncertainty.dat, but it is created by running test.sh. Can the tutorial be changed to run without producing output, perhaps?

**Comment by bobmyhill** [comment]
Ooooh, it's a sed thing. sed -i'' -e is interpreted on my systems as sed -i'-e'.

**Comment by tjhei** [comment]
huh, interesting!

**Comment by tjhei** [comment]
does it work if you do "sed -i -e"? Does it work for you if you remove the "-e" (I have no idea why we do that)?

**Comment by bobmyhill** [comment]
No, but in the sed manual it does warn the user not to leave the backup extension empty (corruption risk). Can I suggest adding a non-null extension, and then removing that files once during each loop?

e.g.
`sed -i'2' -e`
`rm $t.tmp2`

**Comment by tjhei** [comment]
does ``sed -i '' -e ...`` work? (note the space)

> corruption risk

I don't think we care about corruption of some tmp file

**Comment by bobmyhill** [comment]
Yes, adding the space works.

True, it's not doing any damage to the code if it becomes corrupted. I still don't think it's great practise, but if you're happy then I am too.
