### ISSUE TITLE
CIG Jenkins

### ISSUE THREAD

**Issue by tjesser-ucdavis-edu** [geodynamics/burnman#356]
https://jenkins.geodynamics.org is now considered stable, so we are looking to add any CIG projects that are interested in Continuous Integration.

I see that you are already using Timo's Jenkins, but would the Burnman team find it helpful to also have Burnman built on the CIG Jenkins server?

**Comment by bobmyhill** [comment]
Hi @tjesser-ucdavis-edu, yes, I think that would be great! 
Is there anything we need to do (regarding dependencies / set up)?

**Comment by tjesser-ucdavis-edu** [comment]
The way we have this set up for [VirtualQuake](https://github.com/geodynamics/vq), [Rayleigh](https://github.com/geodynamics/Rayleigh), and [Calypso](https://github.com/geodynamics/calypso) seems to work well. We use DockerHub's automatic container builds to allow the project repo to contain the Dockerfile for the build environment (see [geodynamics](https://hub.docker.com/u/geodynamics)) and then create a Jenkinsfile or Jenkinsfile.cig in the project repo.

Having the Dockerfile for the build environment in the repo gives project developers an easy way to keep the build container up-to-date, and allows users to see a very explicit example of the dependencies. The only issue is that the Dockerfile needs to be merged for DockerHub's autobuild to start.

If you want, I can create a pull request for each file. Let me know if any part of the setup is unclear.

**Comment by bobmyhill** [comment]
> If you want, I can create a pull request for each file.

Yes please, that would be great.

The setup makes sense to me in a vague sense. I'll need to dedicate a bit of time to better understand what's going on under the hood. 

At the moment, our dependencies are listed in `sphinx/pip_requirements.txt`. I did intend to link this file with our documentation, but it would be even better to link the documentation with the dockerfile.
