### ISSUE TITLE
Algorithm used to solve the ODE in the planet class

### ISSUE THREAD

**Issue by Huang-CL** [geodynamics/burnman#366]
The `make()` function in the `Planet` class solves a two-point boundary value ODE problems for the "self-consistent" pressure mode.  

The algorithm used to solve the problem is neither the shooting method nor the relaxation method. It iteratively integrates the gravity, pressure, and temperature equations. I'm wondering what is the method used here?  How to guarantee the convergence of this method? Does this method converge faster compared to the traditional shooting method or relaxation method?

Thanks.

**Comment by bobmyhill** [comment]
@Huang-CL I think this is a question for @ian-r-rose, who wrote that bit of the code, but I'll take a first pass.
1) I don't think there's a name for the method. 
2) The method takes a reasonable guess for the increase in pressure with depth, and uses this to calculate rho(r). Using rho(r) and the gravity at the base (g(0) = 0 for a whole planet), g(r) can be calculated by integrating Poisson's equation. The gravity and density profile can then be used to calculate the pressure (by integrating rho*g downwards).
3) We haven't tested other methods, but this method converges within a few iterations, and has been robust for our use-cases.

We would welcome any comments, suggestions and contributions to the code!

**Comment by ian-r-rose** [comment]
@bobmyhill is right -- I wrote the iterative method because it was pretty simple to implement and seemed to converge quickly in testing. There may be better methods, however, so if you want to experiment with others, I'd encourage you to do so!

**Comment by Huang-CL** [comment]
Got you.  Thanks.
