### ISSUE TITLE
Python contrib notebooks don't have outputs

### ISSUE THREAD

**Issue by SauravMaheshkar** [geodynamics/burnman#462]
I was going through the repository and noticed that that the notebooks in the `contib/` dir don't have the saved cell outputs. I'd suggest that the notebooks be saved after running all the cells so that one can just see the notebook outputs and not have to clone and run the example notebooks.

It'd also be nice if there was an **Open in Colab** button at the top of the notebooks.

**Comment by bobmyhill** [comment]
Dear @SauravMaheshkar,

Thank you for raising this issue.
We originally elected not to save the cell outputs for notebooks in the repository for maintenance reasons (it's easier to wipe the outputs than it is to run `git checkout <file>` every time we run a cell). 

One thing we could do is add the (maintained) notebooks to the manual, and link to those manual pages in the ipynb file. We've already added the BurnMan tutorials to the manual: https://burnman.readthedocs.io/en/latest/tutorial.html. 

I'm also happy to see other links added in the ipynb files or in the relevant readmes. At the moment, we're using binder for the BurnMan tutorials (there are links in the GitHub readme, and also on the webpage), which is slightly more flexible than Colab (Colab will only allow users to download published packages, which can be an issue for actively developed projects).

What do you think? Would my suggested changes ((1) manual additions, (2) links to the manual in the ipynbs and (3) links to binder in the ipynbs) be adequate? Is there anything extra that you would like to see?

Are you happy to make a PR for any of these?

Bob

**Comment by SauravMaheshkar** [comment]
Hey @bobmyhill thanks for the elaborate response.

- IMO (2) i.e. adding maintained notebooks to the manuals sounds better than manually adding each cell output to git. But could you clarify this for me. Why not run the entire notebook and "`git add`" the entire saved notebook ?? That way you won't have to run git checkout every time you run a cell
- When seeing the notebooks, I did checkout binder but then again it took like 5 mins for binder to open up on my end which increases the onboarding time and friction. As far as installing actively maintained projects on colab. I'm sure the following command should do the trick

```bash
pip install -e git+https://github.com/geodynamics/burnman.git@master#egg=burnman
```

For reference I've attached a [gist](https://gist.github.com/SauravMaheshkar/d55a66a9d18022a08a520fdd7e7e2dfd), which shows that the following command works.
