### ISSUE TITLE
polytopetools

### ISSUE THREAD

**Issue by stanroozen** [geodynamics/burnman#485]
Hello [Burnman]

I had a question regarding your burnman polytopetools. I tried to modify your examples from your contributions paper to calculate the missing endmembers of my biotite model that i am making (see attachment). However, something strange happens when i use the function:
complete_basis = generate_complete_basis(bi_partial_basis, bi_array)

it automatically replaced one of my original independent endmembers of my partial basis with a new endmember (line 174). However, when i repeat the endmember that gets replaced in my original bi_partial basis this does not happen (line 163 repeated at line 168). 

Many thanks in advance.

Greetings,
Stan
[example_polytopetools_BioD.txt](https://github.com/geodynamics/burnman/files/8807416/example_polytopetools_BioD.txt)

**Comment by bobmyhill** [comment]
Dear @stanroozen,
The PR provided at #486 should solve your problem. 
Our test suite seems not to run in GitHub actions at the moment, but I've checked the output of the test suite and your python file and both seem to work well. 
I'll hold off from merging the PR until I know how to fix the problem with GitHub actions, but you're welcome to pull that branch.

**Comment by stanroozen** [comment]
I just pulled the branch and checked it on my computer. it indeed seems to work! Many thanks

**Comment by stanroozen** [comment]
Hello Bob MyHill,

After I had tested your new solution for the Polytope-tools I found one other oddity.  I calculated new endmembers for another model that i am making for tourmaline. Firstly i found endmembers that i need to add to my existing set to complete the solution space. However the suggested endmembers are not the most practical. Therefore I used your trick that you sent me by e-mail to replace endmembers so i can form a new set always checking that the rank of the matrix stays the same.  However in the attached code i replaced the only F-containing endmember with a non F containing endmember however the rank stays the same. I found this strange as i guess you cannot make dependent F endmembers without F in the independent endmembers.


Does it have to do with the -0 that are generated? or should F be treated differently?

Greetings Stan

[tourmaline_polytope_indep_endmemberwithoutF.txt](https://github.com/geodynamics/burnman/files/8835429/tourmaline_polytope_indep_endmemberwithoutF.txt)

**Comment by bobmyhill** [comment]
Hi @stanroozen, I don't have access to a computer this weekend, will try to have a look on Monday.

It's possible the rank issue is a floating point problem, in which case rewriting the functions using sympy would solve the issue. But I'll need to check.

I have thought about writing a notebook where users could hand pick the most useful set of endmembers for them. Maybe that would be a good thing to do.

**Comment by bobmyhill** [comment]
Hi @stanroozen, sorry for the delay. The rank issue is indeed a floating point problem. You can modify the rank-calculation like this:
`    M = sympy.Matrix([[sympy.Rational(v).limit_denominator(1000)
                       for v in row]
                      for row in complete_basis])`
`print(M.rank(simplify=True))`

This correctly calculates the number of independent row vectors (9 for the complete model, 8 for your modified model).

**Comment by bobmyhill** [comment]
#486 is now updated to use sympy, and merged with the master branch. 
I'll close this issue now, but please reopen it if you're still having issues.

**Comment by stanroozen** [comment]
Hello Robert MyHill,
Your sympy solution works very well! However, by now I have encountered another unexpected behavior in the generate_complete_basis algorithm. 

If I add to my partial basis set a by the polytope function suggested valid charge balanced end member which have occupancies less than 1 atoms for example:

Mg-Dutrowite: Na(Mg2.5Ti0.5)Al OH3 O1

Then the the generate_complete_basis function return 1 more endmember than the rank of the polytope allows (gives me 14 endmembers while only 13 independent ones are allowed)

When adding an endmember that does not have this 0.5 atom occupancy to my partial basis set, there is no problem, eg when i add: Na (Mg2Ti1) Mg O3 F

[example_polytopetools_Tm_XY3Z1V3W_Fef_Ti_ALT_B.txt](https://github.com/geodynamics/burnman/files/9136120/example_polytopetools_Tm_XY3Z1V3W_Fef_Ti_ALT_B.txt)


Greetings Stan Roozen

**Comment by bobmyhill** [comment]
Hi @stanroozen, are you sure your suggested vector is correct? Shouldn't your last three elements be 0 1 0?

**Comment by stanroozen** [comment]
oeps I am sorry. Thanks for the help!
