### ISSUE TITLE
Burnman readable files

### ISSUE THREAD

**Issue by vivianotieno** [geodynamics/burnman#524]
Dear Burnman Community

I have been trying to use the newer version of burnman to create a burnman readable file, and I keep getting the below error: I am using the more recent version of perple_x of v.7.0.9. I have tried the various versions of burnman, and non seem to work. The error comes from the perplex.py file. I have run the Werami file, and the issue might be due to an additional prompt not in the previous versions. Find below are the resulting prompts from running the create-burnman table: 

Keeping P-T range the same as the original project range.

Perple_X release 7.0.9, March 27, 2023.

Copyright (C) 1986-2023 James A D Connolly <www.perplex.ethz.ch/copyright.html>.

Enter the project name (the name assigned in BUILD) [default = my_project]:

Reading Perple_X options from: stx21_perplex_option.dat
Writing Perple_X option summary to: not requested

Perple_X computational option settings for WERAMI:

Keyword:               Value:     Permitted values [default]:

Input/Output options:

aqueous_output          T         [F] T
aqeuous_species         20        [20] 0-150
aq_solvent_composition  y         [y] m: y => mol fraction, m => molality
aq_solute_composition   m         y [m]: y => mol fraction, m => molality
spreadsheet             T         [F] T
logarithmic_p           F         [F] T
logarithmic_X           F         [F] T
bad_number             NaN        [NaN]
composition_constant    F         [F] T
composition_phase       mol       [mol] wt
composition_system      wt        [wt] mol
proportions             vol       [vol] wt mol
absolute                F         [F] T
cumulative              F         [F] T
fancy_cumulative_modes  F         [F] T
interpolation           on        [on] off 
melt_is_fluid           T         [T] F
solution_names          mod       [model] abbreviation full
structural_formulae     T         [T] F
output_species          T         [T] F
output_species_props    F         [F] T
seismic_output          som       [some] none all
pause_on_error          T         [T] F
poisson_test            F         [F] T
interim_results         aut       [auto] off manual
sample_on_grid          T         [T] F

Information file output options:

option_list_files       F         [F] T; echo computational options

Thermodynamic options:

approx_alpha            T         [T] F
Anderson-Gruneisen      F         [F] T
hybrid_EoS_H2O             4      [4] 0-2, 4-7
hybrid_EoS_CO2             4      [4] 0-4, 7
hybrid_EoS_CH4             0      [0] 0-1, 7
fd_expansion_factor     2.0       [2] >0
finite_difference_p     0.1E+05   [1d4] >0; fraction = 0.1E-02   [1d-2]

Seismic wavespeed computational options:

seismic_data_file       T         [F] T
bounds                  VRH       [VRH] HS
vrh/hs_weighting        0.5       [0.5] 0->1
explicit_bulk_modulus   T         [T] F
poisson_ratio           on        [on] all off; Poisson ratio = 0.35
seismic_output          som       [some] none all
poisson_test            F         [F] T
Tisza_test              F         [F] T
fluid_shear_modulus     T         [T] F
phi_d                   0.36      [0.36] 0->1

To change these options see: www.perplex.ethz.ch/perplex_options.html

warning ver099 The P derivative of mu for qtz is < 0, this is improbable.

Select operational mode:
1 - properties at specified conditions
2 - properties on a 2d grid
3 - properties along a 1d path
4 - as in 3, but input from file
0 - EXIT

Select a property:
1 - Specific Enthalpy (J/m3)
2 - Density (kg/m3)
3 - Specific heat capacity (J/K/m3)
4 - Expansivity (1/K, for volume)
5 - Compressibility (1/bar, for volume)
6 - Composition (Mol, Mass, or Wt%) of the system
7 - Mode (Vol, Mol, or Wt proportion) of a phase
8 - Composition (Mol, Mass, or Wt%) of a solution phase
9 - Grueneisen thermal ratio
10 - Adiabatic bulk modulus (bar)
11 - Adiabatic shear modulus (bar)
12 - Sound velocity (km/s)
13 - P-wave velocity (Vp, km/s)
14 - S-wave velocity (Vs, km/s)
15 - Vp/Vs
16 - Specific entropy (J/K/m3)
17 - Entropy (J/K/kg)
18 - Enthalpy (J/kg)
19 - Heat Capacity (J/K/kg)
20 - Specific mass of a phase (kg/m3-system)
21 - Poisson ratio
22 - Molar Volume (J/bar)
23 - Dependent potentials (J/mol, bar, K)
24 - Assemblage Index
25 - Modes of all phases
26 - Sound velocity T derivative (km/s/K)
27 - P-wave velocity T derivative (km/s/K)
28 - S-wave velocity T derivative (km/s/K)
29 - Adiabatic bulk modulus T derivative (bar/K)
30 - Shear modulus T derivative (bar/K)
31 - Sound velocity P derivative (km/s/bar)
32 - P-wave velocity P derivative (km/s/bar)
33 - S-wave velocity P derivative (km/s/bar)
34 - Adiabatic bulk modulus P derivative (unitless)
35 - Shear modulus P derivative (unitless)
36 - All phase &/or system properties
37 - Absolute amount (Vol, Mol, or Wt) of a phase
38 - Multiple property output
39 - Heat capacity ratio (Cp/Cv)
40 - Lagged or back-calculated aqueous solute chemistry

Calculate individual phase properties (y/n)?

Select an additional property or enter 0 to finish:

Calculate individual phase properties (y/n)?

Select an additional property or enter 0 to finish:

Calculate individual phase properties (y/n)?

Select an additional property or enter 0 to finish:

Calculate individual phase properties (y/n)?

Select an additional property or enter 0 to finish:

Calculate individual phase properties (y/n)?

Select an additional property or enter 0 to finish:

Calculate individual phase properties (y/n)?

Select an additional property or enter 0 to finish:

Calculate individual phase properties (y/n)?

Select an additional property or enter 0 to finish:

Calculate individual phase properties (y/n)?

Select an additional property or enter 0 to finish:

Calculate individual phase properties (y/n)?

Select an additional property or enter 0 to finish:

Calculate individual phase properties (y/n)?

Select an additional property or enter 0 to finish:

Calculate individual phase properties (y/n)?

Select an additional property or enter 0 to finish:

Calculate individual phase properties (y/n)?

Select an additional property or enter 0 to finish:

****Change default variable range (y/n)?**** (The prompt to this might be the cause of error or the sample-grid size)

error vertex unspecified error ier=999
real= 0.000000
i= 0
char=user changed grid parms?

Press Enter to quit…

Note: The following floating-point exceptions are signalling: IEEE_INVALID_FLAG IEEE_DIVIDE_BY_ZERO

IndexError Traceback (most recent call last)
/tmp/ipykernel_26312/1766588202.py in
----> 1 create_perplex_table(‘/home/votieno/Work/Perplex/werami’, ‘Earth3’, ‘Earth1stx3’, 2, 2)

~/Work/Burn3/burnman-1.0/burnman/classes/perplex.py in create_perplex_table(werami_path, project_name, outfile, n_pressures, n_temperatures, pressure_range, temperature_range)
65 stdout = p.communicate(input=stdin)[0]
66 print(stdout)
—> 67 out = [s for s in stdout.split(‘\n’) if ‘Output has been written to the’ in s][0].split()[-1]
68 rename(out, outfile)
69 print(‘Output file renamed to {0:s}’.format(outfile))

IndexError: list index out of range

**Comment by Francyrad** [comment]
I had the same problem and i solved just "downgrading" my PerpleX with the version 6.9. I suggest you to do the same until the problem is fixed.

**Comment by bobmyhill** [comment]
Hi @vivianotieno, hi @Francyrad,

I've just got round to having a look at this. PerpleX werami now requires that vertex has already been run, and has some added warning messages for table creation. I'll see if I can find a good code workaround, otherwise I'll add some instructions that should allow you to use PerpleX 7.x with the current BurnMan scripts.

**Comment by Francyrad** [comment]
Dear @bobmyhill 

I did a post in the Aspect forum and I was waiting your answer because you are one of the main developers of Burnman 

https://community.geodynamics.org/t/how-to-use-more-than-a-tabulated-burman-file-in-the-ascii-model/3004

I would love to use more than 2 tabulated files to have more than one compositional field using the ASCII model instead of the steinberger one.

Is there a workaround to do that?

**Comment by bobmyhill** [comment]
@Francyrad yes, I saw your post. I'm working through posts on various fora today - I'll get to yours at some point. Sorry, community support is tricky at certain times of year - especially around now when many of us are marking exams / catching up with other long-overdue tasks.

**Comment by Francyrad** [comment]
Not a problem! Thank you for the availability, i wait a your respond in agreement with your engagements

Francesco

**Comment by bobmyhill** [comment]
It looks like the code doesn't need to be changed, but there are a couple more pre-processing steps to do. 

@vivianotieno : If you still have a problem after following the two steps in the description of  #537, can you attach your build file and your call to `python ~/projects/burnman/misc/create_burnman_readable_perplex_table.py` (i.e. the arguments you provided to the script)? Then I can troubleshoot properly.
