### ISSUE TITLE
Clarification on optional dependencies

### ISSUE THREAD

**Issue by kaylai** [geodynamics/burnman#528]
cvxpy, pycddlib, and autograd are listed in the ReadMe as optional dependencies.

**Issues/questions:**
- What functionality will I lose if I do not install these?
- I was able to easily pip install cvxpy and autograd. Is there a reason you don't include these as standard dependencies that automatically get installed for me when I pip install BurnMan?
- ~~I got a legacy-install-failure error when I tried to pip install pycddlib. Is there another suggested way to install this?~~ *Fixed, see comment below.*

**Suggestions:**
Adding clarity to the ReadMe, specifically what functionality I will lose if I do not install these.

In reference to: https://github.com/openjournals/joss-reviews/issues/5389

**Comment by kaylai** [comment]
Quick update, I worked harder to install pycddlib (I actually read the error message and then googled that...) I am doing this on my work computer, which has frequent updates. I assume one of them knocked out my previous install of XCode command line tools. Following the guidance [here](https://apple.stackexchange.com/questions/254380/why-am-i-getting-an-invalid-active-developer-path-when-attempting-to-use-git-a), I simply did:

`xcode-select --install`

and then tried `pip install pycddlib` again, and it worked. Given your docs also say to make sure XCode is installed, that one is on me!

**Comment by simonwmatthews** [comment]
I agree that this would be a good thing to clarify. 

This is not an issue with burnman, but it might be something that is useful to flag up... I had some issues installing cvxpy on an M1 chip mac, which appears to be a known issue with cvxpy. This problem also meant the test suite (test.sh) would not run properly, though the tutorials do (or at least appear to) run correctly.
