### ISSUE TITLE
Docstrings: Argument names are smooshed together with argument types

### ISSUE THREAD

**Issue by kaylai** [geodynamics/burnman#529]
It seems in most (all?) of the autogenerated documentation from docstrings, the argument types are smooshed (this is a technical term) together with the argument type, so instead of

`myarg float`
or
```
myarg
    float
```

you get
`myargfloat`

which did confuse me quite a bit at fist in some cases!

In reference to: https://github.com/openjournals/joss-reviews/issues/5389

**Comment by bobmyhill** [comment]
Thanks @kaylai, this is now addressed by #541.
