### ISSUE TITLE
ERROR: Failed building wheel for pycddlib-standalone for BurnMan 2.0

### ISSUE THREAD

**Issue by Te-rex83** [geodynamics/burnman#610]
When installing BurnMan from pip, this may fail depending on the python version up to the current 3.13 release.

`    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
          [end of output]
      note: This error originates from a subprocess, and is likely not a problem with pip.
      ERROR: Failed building wheel for pycddlib-standalone
    Failed to build pycddlib-standalone
    ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (pycddlib-standalone)`

The user can go to the Microsoft website and download the online installer for MS Visual C++ 14, but may still be confused what components to download and install. The download is not small either, over 5 GB for a C++ compiler to build wheels for pycddlib.

I'm not sure how to avoid pycddlib, but it seems to be a requirement (i.e. not optional) to install BurnMan. 

It would be best to make this package optional again, and when it is really needed, give a warning.

**Comment by bobmyhill** [comment]
- Thanks for reporting this. Can you confirm that this is a problem only with python 3.13? 
- If so, it might be fixed when pycddlib and pycddlib-standalone 3.0.1 are released: https://github.com/mcmtroffaes/pycddlib/pull/75

**Comment by Te-rex83** [comment]
- The problem exists with all versions of python 3.9 and greater.
- The problem does not exist for version 3.8 and lower because an older version of Burnman is installed...(presumably)
- Note that I can install pycddlib with pip for all versions of python, however the standalone version requires building wheels, which cannot be done without the development tools from Visual C++.

**Comment by bobmyhill** [comment]
@Te-rex83 - To avoid you and other users having to install a working compiler even when you don't need pycddlib functionality, I've removed pycddlib as a required dependency in BurnMan 2.1.0. You should be able to install it using pip.

**Comment by Te-rex83** [comment]
Thank you!
